### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_resolution: 147456
video_resolution: 65536
trust_remote_code: true
use_unsloth_gc: true
flash_attn: fa2
use_fast_tokenizer: true

### method
stage: sft
do_train: false
do_predict: true
finetuning_type: full
video_fps: 4.0

### dataset
#dataset: cmr_videos_sharegpt  # video: mllm_video_demo
eval_dataset: cmr_test_sharegpt
template: qwen2_vl
cutoff_len: 5120
#max_samples: 300
overwrite_cache: true
preprocessing_num_workers: 16
predict_with_generate: true

### output
output_dir: ../../../llamafactory-models/qwen2.5_vl-7b/full/raw-test/
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
per_device_eval_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
#do_eval: false
#eval_strategy: steps
#eval_steps: 500
