### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_resolution: 147456
video_resolution: 65536
trust_remote_code: true
use_unsloth_gc: true
flash_attn: fa2
use_fast_tokenizer: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true  # choices: [true, false]
freeze_multi_modal_projector: true  # choices: [true, false]
train_mm_proj_only: false  # choices: [true, false]
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
video_fps: 4.0

### dataset
dataset: cmr_train_sharegpt
template: qwen2_vl
cutoff_len: 5120
#max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ../../../llamafactory-models/qwen2.5_vl-7b/full/final
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 15.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: false

### eval
#val_size: 0.05
eval_dataset: cmr_val_sharegpt
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
